# Generated by Django 5.2.1 on 2025-05-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nucleotidesequence',
            old_name='content',
            new_name='sequence',
        ),
    ]
