# Generated by Django 5.2.1 on 2025-05-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_content_nucleotidesequence_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleotideChunk',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('chunk_data', models.TextField()),
            ],
            options={
                'unique_together': {('id', 'chunk_index')},
            },
        ),
        migrations.DeleteModel(
            name='NucleotideSequence',
        ),
    ]
