# Generated by Django 5.2.1 on 2025-05-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_nucleotidechunk_delete_nucleotidesequence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nucleotidechunk',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nucleotidechunk',
            name='sequence_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nucleotidechunk',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='nucleotidechunk',
            unique_together={('sequence_id', 'chunk_index')},
        ),
    ]
